// This file is auto-generated by @hey-api/openapi-ts

export type GetLinksOpengraphByDomainIdByLinkIdData = {
    body?: never;
    path: {
        domainId: number;
        linkId: string;
    };
    query?: never;
    url: "/links/opengraph/{domainId}/{linkId}";
};

export type GetLinksOpengraphByDomainIdByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PutLinksOpengraphByDomainIdByLinkIdData = {
    body?: Array<
        [
            (
                | "title"
                | "type"
                | "image"
                | "url"
                | "audio"
                | "description"
                | "determiner"
                | "locale"
                | "locale:alternate"
                | "site_name"
                | "video"
                | "image:url"
                | "image:secure_url"
                | "image:type"
                | "image:width"
                | "image:height"
                | "image:alt"
                | "music:duration"
                | "music:album"
                | "music:album:disc"
                | "music:album:track"
                | "music:musician"
                | "music:song"
                | "music:song:disc"
                | "music:song:track"
                | "music:release_date"
                | "music:creator"
                | "video:actor"
                | "video:actor:role"
                | "video:director"
                | "video:writer"
                | "video:duration"
                | "video:release_date"
                | "video:tag"
                | "video:series"
                | "book:author"
                | "book:isbn"
                | "book:release_date"
                | "book:tag"
                | "profile:first_name"
                | "profile:last_name"
                | "profile:username"
                | "profile:gender"
                | "twitter:card"
                | "twitter:site"
                | "twitter:site:id"
                | "twitter:creator"
                | "twitter:creator:id"
                | "twitter:description"
                | "twitter:title"
                | "twitter:image"
                | "twitter:image:alt"
                | "twitter:player"
                | "twitter:player:width"
                | "twitter:player:height"
                | "twitter:player:stream"
                | "twitter:app:name:iphone"
                | "twitter:app:id:iphone"
                | "twitter:app:url:iphone"
                | "twitter:app:name:ipad"
                | "twitter:app:id:ipad"
                | "twitter:app:url:ipad"
                | "twitter:app:name:googleplay"
                | "twitter:app:id:googleplay"
                | "twitter:app:url:googleplay"
                | "twitter:app:country"
            ),
            string,
        ]
    >;
    path: {
        domainId: number;
        linkId: string;
    };
    query?: never;
    url: "/links/opengraph/{domainId}/{linkId}";
};

export type PutLinksOpengraphByDomainIdByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetLinkCountryByLinkIdData = {
    body?: never;
    path: {
        linkId: string;
    };
    query?: {
        domainId?: string;
    };
    url: "/link_country/{linkId}";
};

export type GetLinkCountryByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinkCountryByLinkIdData = {
    body: {
        /**
         * Country code
         */
        country:
            | "AD"
            | "AE"
            | "AF"
            | "AG"
            | "AI"
            | "AL"
            | "AM"
            | "AO"
            | "AQ"
            | "AR"
            | "AS"
            | "AT"
            | "AU"
            | "AW"
            | "AX"
            | "AZ"
            | "BA"
            | "BB"
            | "BD"
            | "BE"
            | "BF"
            | "BG"
            | "BH"
            | "BI"
            | "BJ"
            | "BL"
            | "BM"
            | "BN"
            | "BO"
            | "BQ"
            | "BR"
            | "BS"
            | "BT"
            | "BV"
            | "BW"
            | "BY"
            | "BZ"
            | "CA"
            | "CC"
            | "CD"
            | "CF"
            | "CG"
            | "CH"
            | "CI"
            | "CK"
            | "CL"
            | "CM"
            | "CN"
            | "CO"
            | "CR"
            | "CU"
            | "CV"
            | "CW"
            | "CX"
            | "CY"
            | "CZ"
            | "DE"
            | "DJ"
            | "DK"
            | "DM"
            | "DO"
            | "DZ"
            | "EC"
            | "EE"
            | "EG"
            | "EH"
            | "ER"
            | "ES"
            | "ET"
            | "FI"
            | "FJ"
            | "FK"
            | "FM"
            | "FO"
            | "FR"
            | "GA"
            | "GB"
            | "GD"
            | "GE"
            | "GF"
            | "GG"
            | "GH"
            | "GI"
            | "GL"
            | "GM"
            | "GN"
            | "GP"
            | "GQ"
            | "GR"
            | "GS"
            | "GT"
            | "GU"
            | "GW"
            | "GY"
            | "HK"
            | "HM"
            | "HN"
            | "HR"
            | "HT"
            | "HU"
            | "ID"
            | "IE"
            | "IL"
            | "IM"
            | "IN"
            | "IO"
            | "IQ"
            | "IR"
            | "IS"
            | "IT"
            | "JE"
            | "JM"
            | "JO"
            | "JP"
            | "KE"
            | "KG"
            | "KH"
            | "KI"
            | "KM"
            | "KN"
            | "KP"
            | "KR"
            | "KW"
            | "KY"
            | "KZ"
            | "LA"
            | "LB"
            | "LC"
            | "LI"
            | "LK"
            | "LR"
            | "LS"
            | "LT"
            | "LU"
            | "LV"
            | "LY"
            | "MA"
            | "MC"
            | "MD"
            | "ME"
            | "MF"
            | "MG"
            | "MH"
            | "MK"
            | "ML"
            | "MM"
            | "MN"
            | "MO"
            | "MP"
            | "MQ"
            | "MR"
            | "MS"
            | "MT"
            | "MU"
            | "MV"
            | "MW"
            | "MX"
            | "MY"
            | "MZ"
            | "NA"
            | "NC"
            | "NE"
            | "NF"
            | "NG"
            | "NI"
            | "NL"
            | "NO"
            | "NP"
            | "NR"
            | "NU"
            | "NZ"
            | "OM"
            | "PA"
            | "PE"
            | "PF"
            | "PG"
            | "PH"
            | "PK"
            | "PL"
            | "PM"
            | "PN"
            | "PR"
            | "PS"
            | "PT"
            | "PW"
            | "PY"
            | "QA"
            | "RE"
            | "RO"
            | "RS"
            | "RU"
            | "RW"
            | "SA"
            | "SB"
            | "SC"
            | "SD"
            | "SE"
            | "SG"
            | "SH"
            | "SI"
            | "SJ"
            | "SK"
            | "SL"
            | "SM"
            | "SN"
            | "SO"
            | "SR"
            | "SS"
            | "ST"
            | "SV"
            | "SX"
            | "SY"
            | "SZ"
            | "TC"
            | "TD"
            | "TF"
            | "TG"
            | "TH"
            | "TJ"
            | "TK"
            | "TL"
            | "TM"
            | "TN"
            | "TO"
            | "TR"
            | "TT"
            | "TV"
            | "TW"
            | "TZ"
            | "UA"
            | "UG"
            | "UM"
            | "US"
            | "UY"
            | "UZ"
            | "VA"
            | "VC"
            | "VE"
            | "VG"
            | "VI"
            | "VN"
            | "VU"
            | "WF"
            | "WS"
            | "YE"
            | "YT"
            | "ZA"
            | "ZM"
            | "ZW"
            | "XK";
        originalURL: string;
    };
    path: {
        linkId: string;
    };
    query?: {
        domainId?: string;
    };
    url: "/link_country/{linkId}";
};

export type PostLinkCountryByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinkCountryBulkByLinkIdData = {
    body?: Array<{
        /**
         * Country code
         */
        country:
            | "AD"
            | "AE"
            | "AF"
            | "AG"
            | "AI"
            | "AL"
            | "AM"
            | "AO"
            | "AQ"
            | "AR"
            | "AS"
            | "AT"
            | "AU"
            | "AW"
            | "AX"
            | "AZ"
            | "BA"
            | "BB"
            | "BD"
            | "BE"
            | "BF"
            | "BG"
            | "BH"
            | "BI"
            | "BJ"
            | "BL"
            | "BM"
            | "BN"
            | "BO"
            | "BQ"
            | "BR"
            | "BS"
            | "BT"
            | "BV"
            | "BW"
            | "BY"
            | "BZ"
            | "CA"
            | "CC"
            | "CD"
            | "CF"
            | "CG"
            | "CH"
            | "CI"
            | "CK"
            | "CL"
            | "CM"
            | "CN"
            | "CO"
            | "CR"
            | "CU"
            | "CV"
            | "CW"
            | "CX"
            | "CY"
            | "CZ"
            | "DE"
            | "DJ"
            | "DK"
            | "DM"
            | "DO"
            | "DZ"
            | "EC"
            | "EE"
            | "EG"
            | "EH"
            | "ER"
            | "ES"
            | "ET"
            | "FI"
            | "FJ"
            | "FK"
            | "FM"
            | "FO"
            | "FR"
            | "GA"
            | "GB"
            | "GD"
            | "GE"
            | "GF"
            | "GG"
            | "GH"
            | "GI"
            | "GL"
            | "GM"
            | "GN"
            | "GP"
            | "GQ"
            | "GR"
            | "GS"
            | "GT"
            | "GU"
            | "GW"
            | "GY"
            | "HK"
            | "HM"
            | "HN"
            | "HR"
            | "HT"
            | "HU"
            | "ID"
            | "IE"
            | "IL"
            | "IM"
            | "IN"
            | "IO"
            | "IQ"
            | "IR"
            | "IS"
            | "IT"
            | "JE"
            | "JM"
            | "JO"
            | "JP"
            | "KE"
            | "KG"
            | "KH"
            | "KI"
            | "KM"
            | "KN"
            | "KP"
            | "KR"
            | "KW"
            | "KY"
            | "KZ"
            | "LA"
            | "LB"
            | "LC"
            | "LI"
            | "LK"
            | "LR"
            | "LS"
            | "LT"
            | "LU"
            | "LV"
            | "LY"
            | "MA"
            | "MC"
            | "MD"
            | "ME"
            | "MF"
            | "MG"
            | "MH"
            | "MK"
            | "ML"
            | "MM"
            | "MN"
            | "MO"
            | "MP"
            | "MQ"
            | "MR"
            | "MS"
            | "MT"
            | "MU"
            | "MV"
            | "MW"
            | "MX"
            | "MY"
            | "MZ"
            | "NA"
            | "NC"
            | "NE"
            | "NF"
            | "NG"
            | "NI"
            | "NL"
            | "NO"
            | "NP"
            | "NR"
            | "NU"
            | "NZ"
            | "OM"
            | "PA"
            | "PE"
            | "PF"
            | "PG"
            | "PH"
            | "PK"
            | "PL"
            | "PM"
            | "PN"
            | "PR"
            | "PS"
            | "PT"
            | "PW"
            | "PY"
            | "QA"
            | "RE"
            | "RO"
            | "RS"
            | "RU"
            | "RW"
            | "SA"
            | "SB"
            | "SC"
            | "SD"
            | "SE"
            | "SG"
            | "SH"
            | "SI"
            | "SJ"
            | "SK"
            | "SL"
            | "SM"
            | "SN"
            | "SO"
            | "SR"
            | "SS"
            | "ST"
            | "SV"
            | "SX"
            | "SY"
            | "SZ"
            | "TC"
            | "TD"
            | "TF"
            | "TG"
            | "TH"
            | "TJ"
            | "TK"
            | "TL"
            | "TM"
            | "TN"
            | "TO"
            | "TR"
            | "TT"
            | "TV"
            | "TW"
            | "TZ"
            | "UA"
            | "UG"
            | "UM"
            | "US"
            | "UY"
            | "UZ"
            | "VA"
            | "VC"
            | "VE"
            | "VG"
            | "VI"
            | "VN"
            | "VU"
            | "WF"
            | "WS"
            | "YE"
            | "YT"
            | "ZA"
            | "ZM"
            | "ZW"
            | "XK";
        originalURL: string;
    }>;
    path: {
        linkId: string;
    };
    query?: {
        domainId?: string;
    };
    url: "/link_country/bulk/{linkId}";
};

export type PostLinkCountryBulkByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteLinkCountryByLinkIdByCountryData = {
    body?: never;
    path: {
        linkId: string;
        /**
         * Country code
         */
        country:
            | "AD"
            | "AE"
            | "AF"
            | "AG"
            | "AI"
            | "AL"
            | "AM"
            | "AO"
            | "AQ"
            | "AR"
            | "AS"
            | "AT"
            | "AU"
            | "AW"
            | "AX"
            | "AZ"
            | "BA"
            | "BB"
            | "BD"
            | "BE"
            | "BF"
            | "BG"
            | "BH"
            | "BI"
            | "BJ"
            | "BL"
            | "BM"
            | "BN"
            | "BO"
            | "BQ"
            | "BR"
            | "BS"
            | "BT"
            | "BV"
            | "BW"
            | "BY"
            | "BZ"
            | "CA"
            | "CC"
            | "CD"
            | "CF"
            | "CG"
            | "CH"
            | "CI"
            | "CK"
            | "CL"
            | "CM"
            | "CN"
            | "CO"
            | "CR"
            | "CU"
            | "CV"
            | "CW"
            | "CX"
            | "CY"
            | "CZ"
            | "DE"
            | "DJ"
            | "DK"
            | "DM"
            | "DO"
            | "DZ"
            | "EC"
            | "EE"
            | "EG"
            | "EH"
            | "ER"
            | "ES"
            | "ET"
            | "FI"
            | "FJ"
            | "FK"
            | "FM"
            | "FO"
            | "FR"
            | "GA"
            | "GB"
            | "GD"
            | "GE"
            | "GF"
            | "GG"
            | "GH"
            | "GI"
            | "GL"
            | "GM"
            | "GN"
            | "GP"
            | "GQ"
            | "GR"
            | "GS"
            | "GT"
            | "GU"
            | "GW"
            | "GY"
            | "HK"
            | "HM"
            | "HN"
            | "HR"
            | "HT"
            | "HU"
            | "ID"
            | "IE"
            | "IL"
            | "IM"
            | "IN"
            | "IO"
            | "IQ"
            | "IR"
            | "IS"
            | "IT"
            | "JE"
            | "JM"
            | "JO"
            | "JP"
            | "KE"
            | "KG"
            | "KH"
            | "KI"
            | "KM"
            | "KN"
            | "KP"
            | "KR"
            | "KW"
            | "KY"
            | "KZ"
            | "LA"
            | "LB"
            | "LC"
            | "LI"
            | "LK"
            | "LR"
            | "LS"
            | "LT"
            | "LU"
            | "LV"
            | "LY"
            | "MA"
            | "MC"
            | "MD"
            | "ME"
            | "MF"
            | "MG"
            | "MH"
            | "MK"
            | "ML"
            | "MM"
            | "MN"
            | "MO"
            | "MP"
            | "MQ"
            | "MR"
            | "MS"
            | "MT"
            | "MU"
            | "MV"
            | "MW"
            | "MX"
            | "MY"
            | "MZ"
            | "NA"
            | "NC"
            | "NE"
            | "NF"
            | "NG"
            | "NI"
            | "NL"
            | "NO"
            | "NP"
            | "NR"
            | "NU"
            | "NZ"
            | "OM"
            | "PA"
            | "PE"
            | "PF"
            | "PG"
            | "PH"
            | "PK"
            | "PL"
            | "PM"
            | "PN"
            | "PR"
            | "PS"
            | "PT"
            | "PW"
            | "PY"
            | "QA"
            | "RE"
            | "RO"
            | "RS"
            | "RU"
            | "RW"
            | "SA"
            | "SB"
            | "SC"
            | "SD"
            | "SE"
            | "SG"
            | "SH"
            | "SI"
            | "SJ"
            | "SK"
            | "SL"
            | "SM"
            | "SN"
            | "SO"
            | "SR"
            | "SS"
            | "ST"
            | "SV"
            | "SX"
            | "SY"
            | "SZ"
            | "TC"
            | "TD"
            | "TF"
            | "TG"
            | "TH"
            | "TJ"
            | "TK"
            | "TL"
            | "TM"
            | "TN"
            | "TO"
            | "TR"
            | "TT"
            | "TV"
            | "TW"
            | "TZ"
            | "UA"
            | "UG"
            | "UM"
            | "US"
            | "UY"
            | "UZ"
            | "VA"
            | "VC"
            | "VE"
            | "VG"
            | "VI"
            | "VN"
            | "VU"
            | "WF"
            | "WS"
            | "YE"
            | "YT"
            | "ZA"
            | "ZM"
            | "ZW"
            | "XK";
    };
    query?: {
        domainId?: string;
    };
    url: "/link_country/{linkId}/{country}";
};

export type DeleteLinkCountryByLinkIdByCountryResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetLinkRegionByLinkIdData = {
    body?: never;
    path: {
        linkId: string;
    };
    query?: {
        domainId?: string;
    };
    url: "/link_region/{linkId}";
};

export type GetLinkRegionByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinkRegionByLinkIdData = {
    body: {
        /**
         * Country code
         */
        country:
            | "AD"
            | "AE"
            | "AF"
            | "AG"
            | "AI"
            | "AL"
            | "AM"
            | "AO"
            | "AQ"
            | "AR"
            | "AS"
            | "AT"
            | "AU"
            | "AW"
            | "AX"
            | "AZ"
            | "BA"
            | "BB"
            | "BD"
            | "BE"
            | "BF"
            | "BG"
            | "BH"
            | "BI"
            | "BJ"
            | "BL"
            | "BM"
            | "BN"
            | "BO"
            | "BQ"
            | "BR"
            | "BS"
            | "BT"
            | "BV"
            | "BW"
            | "BY"
            | "BZ"
            | "CA"
            | "CC"
            | "CD"
            | "CF"
            | "CG"
            | "CH"
            | "CI"
            | "CK"
            | "CL"
            | "CM"
            | "CN"
            | "CO"
            | "CR"
            | "CU"
            | "CV"
            | "CW"
            | "CX"
            | "CY"
            | "CZ"
            | "DE"
            | "DJ"
            | "DK"
            | "DM"
            | "DO"
            | "DZ"
            | "EC"
            | "EE"
            | "EG"
            | "EH"
            | "ER"
            | "ES"
            | "ET"
            | "FI"
            | "FJ"
            | "FK"
            | "FM"
            | "FO"
            | "FR"
            | "GA"
            | "GB"
            | "GD"
            | "GE"
            | "GF"
            | "GG"
            | "GH"
            | "GI"
            | "GL"
            | "GM"
            | "GN"
            | "GP"
            | "GQ"
            | "GR"
            | "GS"
            | "GT"
            | "GU"
            | "GW"
            | "GY"
            | "HK"
            | "HM"
            | "HN"
            | "HR"
            | "HT"
            | "HU"
            | "ID"
            | "IE"
            | "IL"
            | "IM"
            | "IN"
            | "IO"
            | "IQ"
            | "IR"
            | "IS"
            | "IT"
            | "JE"
            | "JM"
            | "JO"
            | "JP"
            | "KE"
            | "KG"
            | "KH"
            | "KI"
            | "KM"
            | "KN"
            | "KP"
            | "KR"
            | "KW"
            | "KY"
            | "KZ"
            | "LA"
            | "LB"
            | "LC"
            | "LI"
            | "LK"
            | "LR"
            | "LS"
            | "LT"
            | "LU"
            | "LV"
            | "LY"
            | "MA"
            | "MC"
            | "MD"
            | "ME"
            | "MF"
            | "MG"
            | "MH"
            | "MK"
            | "ML"
            | "MM"
            | "MN"
            | "MO"
            | "MP"
            | "MQ"
            | "MR"
            | "MS"
            | "MT"
            | "MU"
            | "MV"
            | "MW"
            | "MX"
            | "MY"
            | "MZ"
            | "NA"
            | "NC"
            | "NE"
            | "NF"
            | "NG"
            | "NI"
            | "NL"
            | "NO"
            | "NP"
            | "NR"
            | "NU"
            | "NZ"
            | "OM"
            | "PA"
            | "PE"
            | "PF"
            | "PG"
            | "PH"
            | "PK"
            | "PL"
            | "PM"
            | "PN"
            | "PR"
            | "PS"
            | "PT"
            | "PW"
            | "PY"
            | "QA"
            | "RE"
            | "RO"
            | "RS"
            | "RU"
            | "RW"
            | "SA"
            | "SB"
            | "SC"
            | "SD"
            | "SE"
            | "SG"
            | "SH"
            | "SI"
            | "SJ"
            | "SK"
            | "SL"
            | "SM"
            | "SN"
            | "SO"
            | "SR"
            | "SS"
            | "ST"
            | "SV"
            | "SX"
            | "SY"
            | "SZ"
            | "TC"
            | "TD"
            | "TF"
            | "TG"
            | "TH"
            | "TJ"
            | "TK"
            | "TL"
            | "TM"
            | "TN"
            | "TO"
            | "TR"
            | "TT"
            | "TV"
            | "TW"
            | "TZ"
            | "UA"
            | "UG"
            | "UM"
            | "US"
            | "UY"
            | "UZ"
            | "VA"
            | "VC"
            | "VE"
            | "VG"
            | "VI"
            | "VN"
            | "VU"
            | "WF"
            | "WS"
            | "YE"
            | "YT"
            | "ZA"
            | "ZM"
            | "ZW"
            | "XK";
        /**
         * ISO 3166-2 region code
         */
        region: string;
        originalURL: string;
    };
    path: {
        linkId: string;
    };
    query?: {
        /**
         * Domain ID
         */
        domainId?: number;
    };
    url: "/link_region/{linkId}";
};

export type PostLinkRegionByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetLinkRegionListByCountryData = {
    body?: never;
    path: {
        /**
         * Country code
         */
        country:
            | "AD"
            | "AE"
            | "AF"
            | "AG"
            | "AI"
            | "AL"
            | "AM"
            | "AO"
            | "AQ"
            | "AR"
            | "AS"
            | "AT"
            | "AU"
            | "AW"
            | "AX"
            | "AZ"
            | "BA"
            | "BB"
            | "BD"
            | "BE"
            | "BF"
            | "BG"
            | "BH"
            | "BI"
            | "BJ"
            | "BL"
            | "BM"
            | "BN"
            | "BO"
            | "BQ"
            | "BR"
            | "BS"
            | "BT"
            | "BV"
            | "BW"
            | "BY"
            | "BZ"
            | "CA"
            | "CC"
            | "CD"
            | "CF"
            | "CG"
            | "CH"
            | "CI"
            | "CK"
            | "CL"
            | "CM"
            | "CN"
            | "CO"
            | "CR"
            | "CU"
            | "CV"
            | "CW"
            | "CX"
            | "CY"
            | "CZ"
            | "DE"
            | "DJ"
            | "DK"
            | "DM"
            | "DO"
            | "DZ"
            | "EC"
            | "EE"
            | "EG"
            | "EH"
            | "ER"
            | "ES"
            | "ET"
            | "FI"
            | "FJ"
            | "FK"
            | "FM"
            | "FO"
            | "FR"
            | "GA"
            | "GB"
            | "GD"
            | "GE"
            | "GF"
            | "GG"
            | "GH"
            | "GI"
            | "GL"
            | "GM"
            | "GN"
            | "GP"
            | "GQ"
            | "GR"
            | "GS"
            | "GT"
            | "GU"
            | "GW"
            | "GY"
            | "HK"
            | "HM"
            | "HN"
            | "HR"
            | "HT"
            | "HU"
            | "ID"
            | "IE"
            | "IL"
            | "IM"
            | "IN"
            | "IO"
            | "IQ"
            | "IR"
            | "IS"
            | "IT"
            | "JE"
            | "JM"
            | "JO"
            | "JP"
            | "KE"
            | "KG"
            | "KH"
            | "KI"
            | "KM"
            | "KN"
            | "KP"
            | "KR"
            | "KW"
            | "KY"
            | "KZ"
            | "LA"
            | "LB"
            | "LC"
            | "LI"
            | "LK"
            | "LR"
            | "LS"
            | "LT"
            | "LU"
            | "LV"
            | "LY"
            | "MA"
            | "MC"
            | "MD"
            | "ME"
            | "MF"
            | "MG"
            | "MH"
            | "MK"
            | "ML"
            | "MM"
            | "MN"
            | "MO"
            | "MP"
            | "MQ"
            | "MR"
            | "MS"
            | "MT"
            | "MU"
            | "MV"
            | "MW"
            | "MX"
            | "MY"
            | "MZ"
            | "NA"
            | "NC"
            | "NE"
            | "NF"
            | "NG"
            | "NI"
            | "NL"
            | "NO"
            | "NP"
            | "NR"
            | "NU"
            | "NZ"
            | "OM"
            | "PA"
            | "PE"
            | "PF"
            | "PG"
            | "PH"
            | "PK"
            | "PL"
            | "PM"
            | "PN"
            | "PR"
            | "PS"
            | "PT"
            | "PW"
            | "PY"
            | "QA"
            | "RE"
            | "RO"
            | "RS"
            | "RU"
            | "RW"
            | "SA"
            | "SB"
            | "SC"
            | "SD"
            | "SE"
            | "SG"
            | "SH"
            | "SI"
            | "SJ"
            | "SK"
            | "SL"
            | "SM"
            | "SN"
            | "SO"
            | "SR"
            | "SS"
            | "ST"
            | "SV"
            | "SX"
            | "SY"
            | "SZ"
            | "TC"
            | "TD"
            | "TF"
            | "TG"
            | "TH"
            | "TJ"
            | "TK"
            | "TL"
            | "TM"
            | "TN"
            | "TO"
            | "TR"
            | "TT"
            | "TV"
            | "TW"
            | "TZ"
            | "UA"
            | "UG"
            | "UM"
            | "US"
            | "UY"
            | "UZ"
            | "VA"
            | "VC"
            | "VE"
            | "VG"
            | "VI"
            | "VN"
            | "VU"
            | "WF"
            | "WS"
            | "YE"
            | "YT"
            | "ZA"
            | "ZM"
            | "ZW"
            | "XK";
    };
    query?: never;
    url: "/link_region/list/{country}";
};

export type GetLinkRegionListByCountryResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinkRegionBulkByLinkIdData = {
    body?: Array<{
        /**
         * Country code
         */
        country:
            | "AD"
            | "AE"
            | "AF"
            | "AG"
            | "AI"
            | "AL"
            | "AM"
            | "AO"
            | "AQ"
            | "AR"
            | "AS"
            | "AT"
            | "AU"
            | "AW"
            | "AX"
            | "AZ"
            | "BA"
            | "BB"
            | "BD"
            | "BE"
            | "BF"
            | "BG"
            | "BH"
            | "BI"
            | "BJ"
            | "BL"
            | "BM"
            | "BN"
            | "BO"
            | "BQ"
            | "BR"
            | "BS"
            | "BT"
            | "BV"
            | "BW"
            | "BY"
            | "BZ"
            | "CA"
            | "CC"
            | "CD"
            | "CF"
            | "CG"
            | "CH"
            | "CI"
            | "CK"
            | "CL"
            | "CM"
            | "CN"
            | "CO"
            | "CR"
            | "CU"
            | "CV"
            | "CW"
            | "CX"
            | "CY"
            | "CZ"
            | "DE"
            | "DJ"
            | "DK"
            | "DM"
            | "DO"
            | "DZ"
            | "EC"
            | "EE"
            | "EG"
            | "EH"
            | "ER"
            | "ES"
            | "ET"
            | "FI"
            | "FJ"
            | "FK"
            | "FM"
            | "FO"
            | "FR"
            | "GA"
            | "GB"
            | "GD"
            | "GE"
            | "GF"
            | "GG"
            | "GH"
            | "GI"
            | "GL"
            | "GM"
            | "GN"
            | "GP"
            | "GQ"
            | "GR"
            | "GS"
            | "GT"
            | "GU"
            | "GW"
            | "GY"
            | "HK"
            | "HM"
            | "HN"
            | "HR"
            | "HT"
            | "HU"
            | "ID"
            | "IE"
            | "IL"
            | "IM"
            | "IN"
            | "IO"
            | "IQ"
            | "IR"
            | "IS"
            | "IT"
            | "JE"
            | "JM"
            | "JO"
            | "JP"
            | "KE"
            | "KG"
            | "KH"
            | "KI"
            | "KM"
            | "KN"
            | "KP"
            | "KR"
            | "KW"
            | "KY"
            | "KZ"
            | "LA"
            | "LB"
            | "LC"
            | "LI"
            | "LK"
            | "LR"
            | "LS"
            | "LT"
            | "LU"
            | "LV"
            | "LY"
            | "MA"
            | "MC"
            | "MD"
            | "ME"
            | "MF"
            | "MG"
            | "MH"
            | "MK"
            | "ML"
            | "MM"
            | "MN"
            | "MO"
            | "MP"
            | "MQ"
            | "MR"
            | "MS"
            | "MT"
            | "MU"
            | "MV"
            | "MW"
            | "MX"
            | "MY"
            | "MZ"
            | "NA"
            | "NC"
            | "NE"
            | "NF"
            | "NG"
            | "NI"
            | "NL"
            | "NO"
            | "NP"
            | "NR"
            | "NU"
            | "NZ"
            | "OM"
            | "PA"
            | "PE"
            | "PF"
            | "PG"
            | "PH"
            | "PK"
            | "PL"
            | "PM"
            | "PN"
            | "PR"
            | "PS"
            | "PT"
            | "PW"
            | "PY"
            | "QA"
            | "RE"
            | "RO"
            | "RS"
            | "RU"
            | "RW"
            | "SA"
            | "SB"
            | "SC"
            | "SD"
            | "SE"
            | "SG"
            | "SH"
            | "SI"
            | "SJ"
            | "SK"
            | "SL"
            | "SM"
            | "SN"
            | "SO"
            | "SR"
            | "SS"
            | "ST"
            | "SV"
            | "SX"
            | "SY"
            | "SZ"
            | "TC"
            | "TD"
            | "TF"
            | "TG"
            | "TH"
            | "TJ"
            | "TK"
            | "TL"
            | "TM"
            | "TN"
            | "TO"
            | "TR"
            | "TT"
            | "TV"
            | "TW"
            | "TZ"
            | "UA"
            | "UG"
            | "UM"
            | "US"
            | "UY"
            | "UZ"
            | "VA"
            | "VC"
            | "VE"
            | "VG"
            | "VI"
            | "VN"
            | "VU"
            | "WF"
            | "WS"
            | "YE"
            | "YT"
            | "ZA"
            | "ZM"
            | "ZW"
            | "XK";
        /**
         * ISO 3166-2 region code
         */
        region: string;
        originalURL: string;
    }>;
    path: {
        linkId: string;
    };
    query?: {
        domainId?: number;
    };
    url: "/link_region/bulk/{linkId}";
};

export type PostLinkRegionBulkByLinkIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type DeleteLinkRegionByLinkIdByCountryByRegionData = {
    body?: never;
    path: {
        linkId: string;
        /**
         * Country code
         */
        country:
            | "AD"
            | "AE"
            | "AF"
            | "AG"
            | "AI"
            | "AL"
            | "AM"
            | "AO"
            | "AQ"
            | "AR"
            | "AS"
            | "AT"
            | "AU"
            | "AW"
            | "AX"
            | "AZ"
            | "BA"
            | "BB"
            | "BD"
            | "BE"
            | "BF"
            | "BG"
            | "BH"
            | "BI"
            | "BJ"
            | "BL"
            | "BM"
            | "BN"
            | "BO"
            | "BQ"
            | "BR"
            | "BS"
            | "BT"
            | "BV"
            | "BW"
            | "BY"
            | "BZ"
            | "CA"
            | "CC"
            | "CD"
            | "CF"
            | "CG"
            | "CH"
            | "CI"
            | "CK"
            | "CL"
            | "CM"
            | "CN"
            | "CO"
            | "CR"
            | "CU"
            | "CV"
            | "CW"
            | "CX"
            | "CY"
            | "CZ"
            | "DE"
            | "DJ"
            | "DK"
            | "DM"
            | "DO"
            | "DZ"
            | "EC"
            | "EE"
            | "EG"
            | "EH"
            | "ER"
            | "ES"
            | "ET"
            | "FI"
            | "FJ"
            | "FK"
            | "FM"
            | "FO"
            | "FR"
            | "GA"
            | "GB"
            | "GD"
            | "GE"
            | "GF"
            | "GG"
            | "GH"
            | "GI"
            | "GL"
            | "GM"
            | "GN"
            | "GP"
            | "GQ"
            | "GR"
            | "GS"
            | "GT"
            | "GU"
            | "GW"
            | "GY"
            | "HK"
            | "HM"
            | "HN"
            | "HR"
            | "HT"
            | "HU"
            | "ID"
            | "IE"
            | "IL"
            | "IM"
            | "IN"
            | "IO"
            | "IQ"
            | "IR"
            | "IS"
            | "IT"
            | "JE"
            | "JM"
            | "JO"
            | "JP"
            | "KE"
            | "KG"
            | "KH"
            | "KI"
            | "KM"
            | "KN"
            | "KP"
            | "KR"
            | "KW"
            | "KY"
            | "KZ"
            | "LA"
            | "LB"
            | "LC"
            | "LI"
            | "LK"
            | "LR"
            | "LS"
            | "LT"
            | "LU"
            | "LV"
            | "LY"
            | "MA"
            | "MC"
            | "MD"
            | "ME"
            | "MF"
            | "MG"
            | "MH"
            | "MK"
            | "ML"
            | "MM"
            | "MN"
            | "MO"
            | "MP"
            | "MQ"
            | "MR"
            | "MS"
            | "MT"
            | "MU"
            | "MV"
            | "MW"
            | "MX"
            | "MY"
            | "MZ"
            | "NA"
            | "NC"
            | "NE"
            | "NF"
            | "NG"
            | "NI"
            | "NL"
            | "NO"
            | "NP"
            | "NR"
            | "NU"
            | "NZ"
            | "OM"
            | "PA"
            | "PE"
            | "PF"
            | "PG"
            | "PH"
            | "PK"
            | "PL"
            | "PM"
            | "PN"
            | "PR"
            | "PS"
            | "PT"
            | "PW"
            | "PY"
            | "QA"
            | "RE"
            | "RO"
            | "RS"
            | "RU"
            | "RW"
            | "SA"
            | "SB"
            | "SC"
            | "SD"
            | "SE"
            | "SG"
            | "SH"
            | "SI"
            | "SJ"
            | "SK"
            | "SL"
            | "SM"
            | "SN"
            | "SO"
            | "SR"
            | "SS"
            | "ST"
            | "SV"
            | "SX"
            | "SY"
            | "SZ"
            | "TC"
            | "TD"
            | "TF"
            | "TG"
            | "TH"
            | "TJ"
            | "TK"
            | "TL"
            | "TM"
            | "TN"
            | "TO"
            | "TR"
            | "TT"
            | "TV"
            | "TW"
            | "TZ"
            | "UA"
            | "UG"
            | "UM"
            | "US"
            | "UY"
            | "UZ"
            | "VA"
            | "VC"
            | "VE"
            | "VG"
            | "VI"
            | "VN"
            | "VU"
            | "WF"
            | "WS"
            | "YE"
            | "YT"
            | "ZA"
            | "ZM"
            | "ZW"
            | "XK";
        region: string;
    };
    query?: {
        domainId?: string;
    };
    url: "/link_region/{linkId}/{country}/{region}";
};

export type DeleteLinkRegionByLinkIdByCountryByRegionResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetLinksPermissionsByDomainIdByLinkIdData = {
    body?: never;
    path: {
        domainId: string;
        linkId: string;
    };
    query?: never;
    url: "/links/permissions/{domainId}/{linkId}";
};

export type GetLinksPermissionsByDomainIdByLinkIdErrors = {
    /**
     * Default Response
     */
    403: {
        error: string;
    };
};

export type GetLinksPermissionsByDomainIdByLinkIdError =
    GetLinksPermissionsByDomainIdByLinkIdErrors[keyof GetLinksPermissionsByDomainIdByLinkIdErrors];

export type GetLinksPermissionsByDomainIdByLinkIdResponses = {
    /**
     * Default Response
     */
    200: Array<{
        id: string;
        DomainId: number;
        UserId: number;
        LinkIdString: string;
    }>;
};

export type GetLinksPermissionsByDomainIdByLinkIdResponse =
    GetLinksPermissionsByDomainIdByLinkIdResponses[keyof GetLinksPermissionsByDomainIdByLinkIdResponses];

export type DeleteLinksPermissionsByDomainIdByLinkIdByUserIdData = {
    body?: never;
    path: {
        domainId: number;
        linkId: string;
        userId: string;
    };
    query?: never;
    url: "/links/permissions/{domainId}/{linkId}/{userId}";
};

export type DeleteLinksPermissionsByDomainIdByLinkIdByUserIdErrors = {
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type DeleteLinksPermissionsByDomainIdByLinkIdByUserIdError =
    DeleteLinksPermissionsByDomainIdByLinkIdByUserIdErrors[keyof DeleteLinksPermissionsByDomainIdByLinkIdByUserIdErrors];

export type DeleteLinksPermissionsByDomainIdByLinkIdByUserIdResponses = {
    /**
     * Default Response
     */
    201: {
        success: boolean;
    };
};

export type DeleteLinksPermissionsByDomainIdByLinkIdByUserIdResponse =
    DeleteLinksPermissionsByDomainIdByLinkIdByUserIdResponses[keyof DeleteLinksPermissionsByDomainIdByLinkIdByUserIdResponses];

export type PostLinksPermissionsByDomainIdByLinkIdByUserIdData = {
    body?: never;
    path: {
        domainId: string;
        /**
         * Link ID
         */
        linkId: string;
        userId: string;
    };
    query?: never;
    url: "/links/permissions/{domainId}/{linkId}/{userId}";
};

export type PostLinksPermissionsByDomainIdByLinkIdByUserIdErrors = {
    /**
     * Default Response
     */
    402: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type PostLinksPermissionsByDomainIdByLinkIdByUserIdError =
    PostLinksPermissionsByDomainIdByLinkIdByUserIdErrors[keyof PostLinksPermissionsByDomainIdByLinkIdByUserIdErrors];

export type PostLinksPermissionsByDomainIdByLinkIdByUserIdResponses = {
    /**
     * Default Response
     */
    201: {
        id: string;
        DomainId: number;
        UserId: number;
        /**
         * Link ID
         */
        LinkIdString: string;
    };
};

export type PostLinksPermissionsByDomainIdByLinkIdByUserIdResponse =
    PostLinksPermissionsByDomainIdByLinkIdByUserIdResponses[keyof PostLinksPermissionsByDomainIdByLinkIdByUserIdResponses];

export type GetApiLinksData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Domain ID
         */
        domain_id: number;
        limit?: number;
        idString?: string;
        createdAt?: string;
        beforeDate?: string;
        afterDate?: string;
        dateSortOrder?: "asc" | "desc";
        pageToken?: string;
        folderId?: string;
    };
    url: "/api/links";
};

export type GetApiLinksErrors = {
    /**
     * Default Response
     */
    403: {
        error: string;
    };
};

export type GetApiLinksError = GetApiLinksErrors[keyof GetApiLinksErrors];

export type GetApiLinksResponses = {
    /**
     * Default Response
     */
    200: {
        count: number;
        links: Array<{
            /**
             * Original URL
             */
            originalURL: string;
            /**
             * Cloaking
             */
            cloaking?: boolean;
            /**
             * Link password
             */
            password?: string;
            /**
             * Link expiration date in milliseconds or ISO string
             */
            expiresAt?: number | string;
            /**
             * Expired URL
             */
            expiredURL?: string;
            /**
             * Link title
             */
            title?: string;
            /**
             * Array of link tags
             */
            tags?: Array<string>;
            /**
             * set utm_source parameter to destination link
             */
            utmSource?: string;
            /**
             * set utm_medium parameter to destination link
             */
            utmMedium?: string;
            /**
             * set utm_campaign parameter to destination link
             */
            utmCampaign?: string;
            /**
             * set utm_term parameter to destination link
             */
            utmTerm?: string;
            /**
             * set utm_content parameter to destination link
             */
            utmContent?: string;
            /**
             * Time to live in milliseconds or ISO string
             */
            ttl?: string | number;
            path: string;
            /**
             * Android URL
             */
            androidURL?: string;
            /**
             * iPhone URL
             */
            iphoneURL?: string;
            /**
             * Link creation date in milliseconds
             */
            createdAt?: number | string;
            /**
             * disable link after specified number of clicks
             */
            clicksLimit?: number;
            /**
             * Provide your email to users to get a password
             */
            passwordContact?: boolean;
            /**
             * Skip query string merging
             */
            skipQS?: boolean;
            /**
             * Link is archived
             */
            archived?: boolean;
            /**
             * Split URL
             */
            splitURL?: string;
            /**
             * Split URL percentage
             */
            splitPercent?: number;
            /**
             * Adroll integration
             */
            integrationAdroll?: string;
            /**
             * Facebook integration
             */
            integrationFB?: string;
            /**
             * Google Analytics integration
             */
            integrationGA?: string;
            /**
             * Google Tag Manager integration
             */
            integrationGTM?: string;
            /**
             * Link ID
             */
            idString: string;
            /**
             * Link ID
             */
            id: string;
            /**
             * Short URL
             */
            shortURL: string;
            /**
             * Secure short URL
             */
            secureShortURL: string;
            /**
             * HTTP code for redirect
             */
            redirectType?: "301" | "302" | "307" | "308";
            /**
             * Folder ID
             */
            FolderId?: string;
            /**
             * Domain ID
             */
            DomainId?: number;
            /**
             * Owner ID
             */
            OwnerId?: number;
            /**
             * Link has password
             */
            hasPassword?: boolean;
            /**
             * Link source
             */
            source?: "website" | "api" | "public" | "spreadsheets" | "slack" | "telegram";
            User?: {
                /**
                 * Creator user ID
                 */
                id: number;
                /**
                 * Creator name
                 */
                name: string;
                /**
                 * Creator email
                 */
                email: string;
                /**
                 * User photo URL
                 */
                photoURL: string;
            };
        }>;
        nextPageToken?: string;
    };
};

export type GetApiLinksResponse = GetApiLinksResponses[keyof GetApiLinksResponses];

export type PostLinksQrByLinkIdStringData = {
    body: {
        color?: string;
        backgroundColor?: string;
        size?: number;
        type?: "png" | "svg";
        useDomainSettings: boolean;
    };
    path: {
        /**
         * Link ID
         */
        linkIdString: string;
    };
    query?: never;
    url: "/links/qr/{linkIdString}";
};

export type PostLinksQrByLinkIdStringResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinksQrBulkData = {
    body: {
        color?: string;
        backgroundColor?: string;
        size?: number;
        type: "png" | "svg";
        useDomainSettings: boolean;
        noExcavate?: boolean;
        linkIds: Array<string>;
        domainId?: string;
    };
    url: "/links/qr/bulk";
};

export type PostLinksQrBulkResponses = {
    /**
     * Zip file with QR codes
     */
    201: Blob | File;
};

export type PostLinksQrBulkResponse = PostLinksQrBulkResponses[keyof PostLinksQrBulkResponses];

export type DeleteLinksByLinkIdData = {
    body?: never;
    path: {
        /**
         * Link ID
         */
        link_id: string;
    };
    query?: never;
    url: "/links/{link_id}";
};

export type DeleteLinksByLinkIdResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
        /**
         * Link ID
         */
        idString?: string;
        error?: string;
    };
};

export type DeleteLinksByLinkIdResponse = DeleteLinksByLinkIdResponses[keyof DeleteLinksByLinkIdResponses];

export type DeleteLinksDeleteBulkData = {
    body: {
        link_ids: Array<string>;
    };
    url: "/links/delete_bulk";
};

export type DeleteLinksDeleteBulkResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
        error?: string;
    };
};

export type DeleteLinksDeleteBulkResponse = DeleteLinksDeleteBulkResponses[keyof DeleteLinksDeleteBulkResponses];

export type PostLinksArchiveData = {
    body: {
        link_id: string;
        domain_id?: string;
    };
    url: "/links/archive";
};

export type PostLinksArchiveErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
        message?: string;
    };
};

export type PostLinksArchiveError = PostLinksArchiveErrors[keyof PostLinksArchiveErrors];

export type PostLinksArchiveResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
        error?: string;
    };
};

export type PostLinksArchiveResponse = PostLinksArchiveResponses[keyof PostLinksArchiveResponses];

export type PostLinksArchiveBulkData = {
    body: {
        link_ids: Array<string>;
        domain_id?: string;
    };
    url: "/links/archive_bulk";
};

export type PostLinksArchiveBulkErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
        message?: string;
    };
};

export type PostLinksArchiveBulkError = PostLinksArchiveBulkErrors[keyof PostLinksArchiveBulkErrors];

export type PostLinksArchiveBulkResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
        error?: string;
    };
};

export type PostLinksArchiveBulkResponse = PostLinksArchiveBulkResponses[keyof PostLinksArchiveBulkResponses];

export type PostLinksUnarchiveData = {
    body: {
        link_id: string;
        domain_id?: string;
    };
    url: "/links/unarchive";
};

export type PostLinksUnarchiveErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
        message?: string;
    };
};

export type PostLinksUnarchiveError = PostLinksUnarchiveErrors[keyof PostLinksUnarchiveErrors];

export type PostLinksUnarchiveResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
        error?: string;
    };
};

export type PostLinksUnarchiveResponse = PostLinksUnarchiveResponses[keyof PostLinksUnarchiveResponses];

export type PostLinksUnarchiveBulkData = {
    body: {
        link_ids: Array<string>;
        domain_id?: string;
    };
    url: "/links/unarchive_bulk";
};

export type PostLinksUnarchiveBulkErrors = {
    /**
     * Default Response
     */
    400: {
        error: string;
        message?: string;
    };
};

export type PostLinksUnarchiveBulkError = PostLinksUnarchiveBulkErrors[keyof PostLinksUnarchiveBulkErrors];

export type PostLinksUnarchiveBulkResponses = {
    /**
     * Default Response
     */
    200: {
        success: boolean;
        error?: string;
    };
};

export type PostLinksUnarchiveBulkResponse = PostLinksUnarchiveBulkResponses[keyof PostLinksUnarchiveBulkResponses];

export type GetLinksByLinkIdData = {
    body?: never;
    path: {
        linkId: string;
    };
    query?: {
        /**
         * [DEPRECATED] Domain ID
         */
        domainId?: string;
    };
    url: "/links/{linkId}";
};

export type GetLinksByLinkIdErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetLinksByLinkIdError = GetLinksByLinkIdErrors[keyof GetLinksByLinkIdErrors];

export type GetLinksByLinkIdResponses = {
    /**
     * Default Response
     */
    200: {
        /**
         * Original URL
         */
        originalURL: string;
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        path: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        /**
         * Skip query string merging
         */
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        /**
         * Link ID
         */
        idString: string;
        /**
         * Link ID
         */
        id: string;
        /**
         * Short URL
         */
        shortURL: string;
        /**
         * Secure short URL
         */
        secureShortURL: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: "301" | "302" | "307" | "308";
        /**
         * Folder ID
         */
        FolderId?: string;
        /**
         * Domain ID
         */
        DomainId?: number;
        /**
         * Owner ID
         */
        OwnerId?: number;
        /**
         * Link has password
         */
        hasPassword?: boolean;
        /**
         * Link source
         */
        source?: "website" | "api" | "public" | "spreadsheets" | "slack" | "telegram";
        User?: {
            /**
             * Creator user ID
             */
            id: number;
            /**
             * Creator name
             */
            name: string;
            /**
             * Creator email
             */
            email: string;
            /**
             * User photo URL
             */
            photoURL: string;
        };
    };
};

export type GetLinksByLinkIdResponse = GetLinksByLinkIdResponses[keyof GetLinksByLinkIdResponses];

export type PostLinksByLinkIdData = {
    body?: {
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: 301 | 302 | 307 | 308;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        /**
         * Link slug
         */
        path?: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        /**
         * Original URL
         */
        originalURL?: string;
    };
    path: {
        linkId: string;
    };
    query?: {
        domain_id?: string;
    };
    url: "/links/{linkId}";
};

export type PostLinksByLinkIdErrors = {
    /**
     * Default Response
     */
    400: {
        message: string;
        field?: string;
    };
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostLinksByLinkIdError = PostLinksByLinkIdErrors[keyof PostLinksByLinkIdErrors];

export type PostLinksByLinkIdResponses = {
    /**
     * Default Response
     */
    200: {
        /**
         * Original URL
         */
        originalURL: string;
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        path: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        /**
         * Skip query string merging
         */
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        /**
         * Link ID
         */
        idString: string;
        /**
         * Link ID
         */
        id: string;
        /**
         * Short URL
         */
        shortURL: string;
        /**
         * Secure short URL
         */
        secureShortURL: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: "301" | "302" | "307" | "308";
        /**
         * Folder ID
         */
        FolderId?: string;
        /**
         * Domain ID
         */
        DomainId?: number;
        /**
         * Owner ID
         */
        OwnerId?: number;
        /**
         * Link has password
         */
        hasPassword?: boolean;
        /**
         * Link source
         */
        source?: "website" | "api" | "public" | "spreadsheets" | "slack" | "telegram";
        User?: {
            /**
             * Creator user ID
             */
            id: number;
            /**
             * Creator name
             */
            name: string;
            /**
             * Creator email
             */
            email: string;
            /**
             * User photo URL
             */
            photoURL: string;
        };
    };
};

export type PostLinksByLinkIdResponse = PostLinksByLinkIdResponses[keyof PostLinksByLinkIdResponses];

export type GetLinksExpandData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Domain hostname
         */
        domain: string;
        /**
         * Link path
         */
        path: string;
    };
    url: "/links/expand";
};

export type GetLinksExpandErrors = {
    /**
     * Default Response
     */
    404: {
        error: string;
    };
};

export type GetLinksExpandError = GetLinksExpandErrors[keyof GetLinksExpandErrors];

export type GetLinksExpandResponses = {
    /**
     * Default Response
     */
    200: {
        /**
         * Original URL
         */
        originalURL: string;
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        path: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        /**
         * Skip query string merging
         */
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        /**
         * Link ID
         */
        idString: string;
        /**
         * Link ID
         */
        id: string;
        /**
         * Short URL
         */
        shortURL: string;
        /**
         * Secure short URL
         */
        secureShortURL: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: "301" | "302" | "307" | "308";
        /**
         * Folder ID
         */
        FolderId?: string;
        /**
         * Domain ID
         */
        DomainId?: number;
        /**
         * Owner ID
         */
        OwnerId?: number;
        /**
         * Link has password
         */
        hasPassword?: boolean;
        /**
         * Link source
         */
        source?: "website" | "api" | "public" | "spreadsheets" | "slack" | "telegram";
        User?: {
            /**
             * Creator user ID
             */
            id: number;
            /**
             * Creator name
             */
            name: string;
            /**
             * Creator email
             */
            email: string;
            /**
             * User photo URL
             */
            photoURL: string;
        };
    };
};

export type GetLinksExpandResponse = GetLinksExpandResponses[keyof GetLinksExpandResponses];

export type GetLinksByOriginalUrlData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Domain hostname
         */
        domain: string;
        /**
         * Link original URL
         */
        originalURL: string;
    };
    url: "/links/by-original-url";
};

export type GetLinksByOriginalUrlResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetLinksMultipleByUrlData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Domain hostname
         */
        domain: string;
        /**
         * Link original URL
         */
        originalURL: string;
    };
    url: "/links/multiple-by-url";
};

export type GetLinksMultipleByUrlResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinksData = {
    body: {
        /**
         * Original URL
         */
        originalURL: string;
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: 301 | 302 | 307 | 308;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        /**
         * Link slug
         */
        path?: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        /**
         * Domain hostname
         */
        domain: string;
        /**
         * Allow duplicates
         */
        allowDuplicates?: boolean;
        /**
         * Folder ID
         */
        folderId?: string;
    };
    url: "/links";
};

export type PostLinksErrors = {
    /**
     * Default Response
     */
    400: {
        code?: string;
        message: string;
        success?: boolean;
        statusCode: number;
    };
};

export type PostLinksError = PostLinksErrors[keyof PostLinksErrors];

export type PostLinksResponses = {
    /**
     * Default Response
     */
    200: {
        /**
         * Original URL
         */
        originalURL: string;
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        path: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        /**
         * Skip query string merging
         */
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        /**
         * Link ID
         */
        idString: string;
        /**
         * Link ID
         */
        id: string;
        /**
         * Short URL
         */
        shortURL: string;
        /**
         * Secure short URL
         */
        secureShortURL: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: "301" | "302" | "307" | "308";
        /**
         * Folder ID
         */
        FolderId?: string;
        /**
         * Domain ID
         */
        DomainId?: number;
        /**
         * Owner ID
         */
        OwnerId?: number;
        /**
         * Link has password
         */
        hasPassword?: boolean;
        /**
         * Link source
         */
        source?: "website" | "api" | "public" | "spreadsheets" | "slack" | "telegram";
        User?: {
            /**
             * Creator user ID
             */
            id: number;
            /**
             * Creator name
             */
            name: string;
            /**
             * Creator email
             */
            email: string;
            /**
             * User photo URL
             */
            photoURL: string;
        };
        success?: boolean;
        duplicate?: boolean;
    };
};

export type PostLinksResponse = PostLinksResponses[keyof PostLinksResponses];

export type GetLinksTweetbotData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Domain hostname
         */
        domain: string;
        /**
         * Link path
         */
        path?: string;
        /**
         * Link original URL
         */
        originalURL: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Return only URL
         */
        urlOnly?: boolean;
        /**
         * API key
         */
        apiKey: string;
    };
    url: "/links/tweetbot";
};

export type GetLinksTweetbotResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinksPublicData = {
    body: {
        /**
         * Original URL
         */
        originalURL: string;
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: 301 | 302 | 307 | 308;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        /**
         * Link slug
         */
        path?: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        /**
         * Skip query string merging
         */
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        domain: string;
        folderId?: string;
    };
    url: "/links/public";
};

export type PostLinksPublicErrors = {
    /**
     * Default Response
     */
    400: {
        code?: string;
        message: string;
        success?: boolean;
        statusCode: number;
    };
};

export type PostLinksPublicError = PostLinksPublicErrors[keyof PostLinksPublicErrors];

export type PostLinksPublicResponses = {
    /**
     * Default Response
     */
    200: {
        /**
         * Original URL
         */
        originalURL: string;
        /**
         * Cloaking
         */
        cloaking?: boolean;
        /**
         * Link password
         */
        password?: string;
        /**
         * Link expiration date in milliseconds or ISO string
         */
        expiresAt?: number | string;
        /**
         * Expired URL
         */
        expiredURL?: string;
        /**
         * Link title
         */
        title?: string;
        /**
         * Array of link tags
         */
        tags?: Array<string>;
        /**
         * set utm_source parameter to destination link
         */
        utmSource?: string;
        /**
         * set utm_medium parameter to destination link
         */
        utmMedium?: string;
        /**
         * set utm_campaign parameter to destination link
         */
        utmCampaign?: string;
        /**
         * set utm_term parameter to destination link
         */
        utmTerm?: string;
        /**
         * set utm_content parameter to destination link
         */
        utmContent?: string;
        /**
         * Time to live in milliseconds or ISO string
         */
        ttl?: string | number;
        path: string;
        /**
         * Android URL
         */
        androidURL?: string;
        /**
         * iPhone URL
         */
        iphoneURL?: string;
        /**
         * Link creation date in milliseconds
         */
        createdAt?: number | string;
        /**
         * disable link after specified number of clicks
         */
        clicksLimit?: number;
        /**
         * Provide your email to users to get a password
         */
        passwordContact?: boolean;
        /**
         * Skip query string merging
         */
        skipQS?: boolean;
        /**
         * Link is archived
         */
        archived?: boolean;
        /**
         * Split URL
         */
        splitURL?: string;
        /**
         * Split URL percentage
         */
        splitPercent?: number;
        /**
         * Adroll integration
         */
        integrationAdroll?: string;
        /**
         * Facebook integration
         */
        integrationFB?: string;
        /**
         * Google Analytics integration
         */
        integrationGA?: string;
        /**
         * Google Tag Manager integration
         */
        integrationGTM?: string;
        /**
         * Link ID
         */
        idString: string;
        /**
         * Link ID
         */
        id: string;
        /**
         * Short URL
         */
        shortURL: string;
        /**
         * Secure short URL
         */
        secureShortURL: string;
        /**
         * HTTP code for redirect
         */
        redirectType?: "301" | "302" | "307" | "308";
        /**
         * Folder ID
         */
        FolderId?: string;
        /**
         * Domain ID
         */
        DomainId?: number;
        /**
         * Owner ID
         */
        OwnerId?: number;
        /**
         * Link has password
         */
        hasPassword?: boolean;
        /**
         * Link source
         */
        source?: "website" | "api" | "public" | "spreadsheets" | "slack" | "telegram";
        User?: {
            /**
             * Creator user ID
             */
            id: number;
            /**
             * Creator name
             */
            name: string;
            /**
             * Creator email
             */
            email: string;
            /**
             * User photo URL
             */
            photoURL: string;
        };
        success?: boolean;
        duplicate?: boolean;
    };
};

export type PostLinksPublicResponse = PostLinksPublicResponses[keyof PostLinksPublicResponses];

export type PostLinksBulkData = {
    body: {
        domain: string;
        allowDuplicates?: boolean;
        links: Array<{
            allowDuplicates?: boolean;
            /**
             * Original URL
             */
            originalURL: string;
            /**
             * Cloaking
             */
            cloaking?: boolean;
            /**
             * Link password
             */
            password?: string;
            /**
             * HTTP code for redirect
             */
            redirectType?: 301 | 302 | 307 | 308;
            /**
             * Link expiration date in milliseconds or ISO string
             */
            expiresAt?: number | string;
            /**
             * Expired URL
             */
            expiredURL?: string;
            /**
             * Link title
             */
            title?: string;
            /**
             * Array of link tags
             */
            tags?: Array<string>;
            /**
             * set utm_source parameter to destination link
             */
            utmSource?: string;
            /**
             * set utm_medium parameter to destination link
             */
            utmMedium?: string;
            /**
             * set utm_campaign parameter to destination link
             */
            utmCampaign?: string;
            /**
             * set utm_term parameter to destination link
             */
            utmTerm?: string;
            /**
             * set utm_content parameter to destination link
             */
            utmContent?: string;
            /**
             * Time to live in milliseconds or ISO string
             */
            ttl?: string | number;
            /**
             * Link slug
             */
            path?: string;
            /**
             * Android URL
             */
            androidURL?: string;
            /**
             * iPhone URL
             */
            iphoneURL?: string;
            /**
             * Link creation date in milliseconds
             */
            createdAt?: number | string;
            /**
             * disable link after specified number of clicks
             */
            clicksLimit?: number;
            /**
             * Provide your email to users to get a password
             */
            passwordContact?: boolean;
            /**
             * Skip query string merging
             */
            skipQS?: boolean;
            /**
             * Link is archived
             */
            archived?: boolean;
            /**
             * Split URL
             */
            splitURL?: string;
            /**
             * Split URL percentage
             */
            splitPercent?: number;
            /**
             * Adroll integration
             */
            integrationAdroll?: string;
            /**
             * Facebook integration
             */
            integrationFB?: string;
            /**
             * Google Analytics integration
             */
            integrationGA?: string;
            /**
             * Google Tag Manager integration
             */
            integrationGTM?: string;
        }>;
        /**
         * Folder ID
         */
        folderId?: string;
    };
    url: "/links/bulk";
};

export type PostLinksBulkResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiDomainsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        noTeamId?: boolean;
        pattern?: string;
        teamId?: number;
    };
    url: "/api/domains";
};

export type GetApiDomainsResponses = {
    /**
     * Default Response
     */
    200: Array<{
        /**
         * Domain ID
         */
        id: number;
        hostname: string;
        unicodeHostname: string;
        state:
            | "extra_records"
            | "not_registered"
            | "configured"
            | "not_configured"
            | "registration_pending"
            | "not_verified";
        createdAt: string;
        updatedAt: string;
        TeamId?: number;
        hasFavicon: boolean;
        segmentKey?: string;
        hideReferer: boolean;
        linkType: "increment" | "random" | "secure" | "four-char" | "eight-char" | "ten-char";
        /**
         * Enable cloaking for all links on the domain
         */
        cloaking: boolean;
        /**
         * Don't store visitor IPs in our database
         */
        hideVisitorIp: boolean;
        /**
         * Enable AI for all links on the domain
         */
        enableAI: boolean;
        httpsLevel: "none" | "redirect" | "hsts";
        httpsLinks: boolean;
        webhookURL?: string;
        integrationGA?: string;
        integrationFB?: string;
        integrationAdroll?: string;
        integrationGTM?: string;
        clientStorage: {};
        caseSensitive: boolean;
        incrementCounter: string;
        robots: "allow" | "disallow" | "noindex";
        sslCertExpirationDate?: string;
        sslCertInstalledSuccess?: boolean;
        domainRegistrationId?: number;
        UserId?: number;
        exportEnabled: boolean;
        isFavorite: boolean;
    }>;
};

export type GetApiDomainsResponse = GetApiDomainsResponses[keyof GetApiDomainsResponses];

export type GetDomainsByDomainIdData = {
    body?: never;
    path: {
        domainId: number;
    };
    query?: never;
    url: "/domains/{domainId}";
};

export type GetDomainsByDomainIdErrors = {
    /**
     * Default Response
     */
    403: {
        error: string;
    };
};

export type GetDomainsByDomainIdError = GetDomainsByDomainIdErrors[keyof GetDomainsByDomainIdErrors];

export type GetDomainsByDomainIdResponses = {
    /**
     * Default Response
     */
    200: {
        /**
         * Domain ID
         */
        id: number;
        hostname: string;
        unicodeHostname: string;
        state:
            | "extra_records"
            | "not_registered"
            | "configured"
            | "not_configured"
            | "registration_pending"
            | "not_verified";
        createdAt: string;
        updatedAt: string;
        TeamId?: number;
        hasFavicon: boolean;
        segmentKey?: string;
        hideReferer: boolean;
        linkType: "increment" | "random" | "secure" | "four-char" | "eight-char" | "ten-char";
        /**
         * Enable cloaking for all links on the domain
         */
        cloaking: boolean;
        /**
         * Don't store visitor IPs in our database
         */
        hideVisitorIp: boolean;
        /**
         * Enable AI for all links on the domain
         */
        enableAI: boolean;
        httpsLevel: "none" | "redirect" | "hsts";
        httpsLinks: boolean;
        webhookURL?: string;
        integrationGA?: string;
        integrationFB?: string;
        integrationAdroll?: string;
        integrationGTM?: string;
        clientStorage: {};
        caseSensitive: boolean;
        incrementCounter: string;
        robots: "allow" | "disallow" | "noindex";
        sslCertExpirationDate?: string;
        sslCertInstalledSuccess?: boolean;
        domainRegistrationId?: number;
        UserId?: number;
        exportEnabled: boolean;
        ipExclusions: Array<string>;
        userPlan: "tiny" | "hobby" | "small" | "standard" | "large";
    };
};

export type GetDomainsByDomainIdResponse = GetDomainsByDomainIdResponses[keyof GetDomainsByDomainIdResponses];

export type PostDomainsData = {
    body: {
        /**
         * Domain hostname
         */
        hostname: string;
        hideReferer?: boolean;
        linkType?: "increment" | "random" | "secure" | "four-char" | "eight-char" | "ten-char";
    };
    url: "/domains";
};

export type PostDomainsErrors = {
    /**
     * Default Response
     */
    402: {
        error: string;
    };
    /**
     * Default Response
     */
    403: {
        error: string;
    };
    /**
     * Default Response
     */
    409: {
        error: string;
    };
};

export type PostDomainsError = PostDomainsErrors[keyof PostDomainsErrors];

export type PostDomainsResponses = {
    /**
     * Default Response
     */
    200: {
        /**
         * Domain ID
         */
        id: number;
        hostname: string;
        unicodeHostname: string;
        state:
            | "extra_records"
            | "not_registered"
            | "configured"
            | "not_configured"
            | "registration_pending"
            | "not_verified";
        createdAt: string;
        updatedAt: string;
        TeamId?: number;
        hasFavicon: boolean;
        segmentKey?: string;
        hideReferer: boolean;
        linkType: "increment" | "random" | "secure" | "four-char" | "eight-char" | "ten-char";
        /**
         * Enable cloaking for all links on the domain
         */
        cloaking: boolean;
        /**
         * Don't store visitor IPs in our database
         */
        hideVisitorIp: boolean;
        /**
         * Enable AI for all links on the domain
         */
        enableAI: boolean;
        httpsLevel: "none" | "redirect" | "hsts";
        httpsLinks: boolean;
        webhookURL?: string;
        integrationGA?: string;
        integrationFB?: string;
        integrationAdroll?: string;
        integrationGTM?: string;
        clientStorage: {};
        caseSensitive: boolean;
        incrementCounter: string;
        robots: "allow" | "disallow" | "noindex";
        sslCertExpirationDate?: string;
        sslCertInstalledSuccess?: boolean;
        domainRegistrationId?: number;
        UserId?: number;
        exportEnabled: boolean;
    };
};

export type PostDomainsResponse = PostDomainsResponses[keyof PostDomainsResponses];

export type PostDomainsSettingsByDomainIdData = {
    body?: {
        httpsLevel?: "none" | "redirect" | "hsts";
        robots?: "allow" | "disallow" | "noindex";
        segmentKey?: string;
        linkType?: "increment" | "random" | "secure" | "four-char" | "eight-char" | "ten-char";
        /**
         * Enable cloaking for all links on the domain
         */
        cloaking?: boolean;
        hideReferer?: boolean;
        /**
         * Don't store visitor IPs in our database
         */
        hideVisitorIp?: boolean;
        /**
         * Set to null to reissue a certificate
         */
        httpsLinks?: boolean;
        webhookURL?: string;
        integrationGA?: string;
        integrationFB?: string;
        integrationAdroll?: string;
        integrationGTM?: string;
        /**
         * For internal use
         */
        clientStorage?: {};
        /**
         * [DEPRECATED] do not use
         */
        purgeExpiredLinks?: boolean;
        enableAI?: boolean;
        /**
         * Enable case sensitivity for short links
         */
        caseSensitive?: boolean;
    };
    path: {
        domainId: number;
    };
    query?: never;
    url: "/domains/settings/{domainId}";
};

export type PostDomainsSettingsByDomainIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostTagsBulkData = {
    body: {
        tag: string;
        link_ids: Array<string>;
    };
    url: "/tags/bulk";
};

export type PostTagsBulkResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetLinksFoldersByDomainIdData = {
    body?: never;
    path: {
        domainId: number;
    };
    query?: never;
    url: "/links/folders/{domainId}";
};

export type GetLinksFoldersByDomainIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetLinksFoldersByDomainIdByFolderIdData = {
    body?: never;
    path: {
        domainId: number;
        folderId: string;
    };
    query?: never;
    url: "/links/folders/{domainId}/{folderId}";
};

export type GetLinksFoldersByDomainIdByFolderIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostLinksFoldersData = {
    body: {
        domainId: number;
        name: string;
        color?: string;
        backgroundColor?: string;
        logoUrl?: string;
        logoHeight?: number;
        logoWidth?: number;
        ecLevel?: string;
        integrationFB?: string;
        integrationGA?: string;
        integrationGTM?: string;
        integrationAdroll?: string;
        utmCampaign?: string;
        utmMedium?: string;
        utmSource?: string;
        redirectType?: number;
        expiresAtDays?: number;
        icon?: string;
        prefix?: string;
    };
    url: "/links/folders";
};

export type PostLinksFoldersResponses = {
    /**
     * Default Response
     */
    200: unknown;
};
